//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingEntities : DbContext
    {
        public MeetingEntities()
            : base("name=MeetingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Corporate_Customer_Tbl> Corporate_Customer_Tbl { get; set; }
        public virtual DbSet<Individual_Customer_Tbl> Individual_Customer_Tbl { get; set; }
        public virtual DbSet<Products_Service_Tbl> Products_Service_Tbl { get; set; }
        public virtual DbSet<Meeting_Minutes_Details_Tbl> Meeting_Minutes_Details_Tbl { get; set; }
        public virtual DbSet<Meeting_Minutes_Master_Tbl> Meeting_Minutes_Master_Tbl { get; set; }
    }
}
