//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Service_Tbl
    {
        public int ProductServiceId { get; set; }
        public string Unit { get; set; }
        public int Quantity { get; set; }
        public string Name { get; set; }
    }
}
